pplu/aws-sdk-perl

lib/Paws/Net/Caller.pm

Prevent Paws::Net::Caller from crashing upon not receiving and object

Prevent Paws::Net::Caller from crashing upon not receiving and object

---

t/10_responses.t
t/10_responses/elasticbeanstalk-create-configuration-template.response

Hi,
There were some unicode related test failures in 10_responses.t. 
From http://www.cpantesters.org/cpan/report/7e730056-40bd-11e5-a85a-e28fcaadd3a7 :
```
land'
```
This pull requests slurps the data files with utf8 encoding and removes a few unprintable chars from one of the data files.
Thanks!

Fix test failures: some utf8 issues in 10_responses.t 

---

lib/Paws/Net/JsonCaller.pm
lib/Paws/Net/V2Signature.pm
lib/Paws/Net/V4Signature.pm

Otherwise the signature can be invalid if the second ticks over
between the X-Amz-Date and Date headers being set, since
Net::Amazon::Signature::V4 only uses Date, but Amazon prefers
X-Amz-Date.
Net::Amazon::Signature::V4 also needs fixing to use X-Amz-Date, but
the patch in https://rt.cpan.org/Public/Bug/Display.html?id=100964
hasn't been applied yet.

Make sure all request timestamps are in sync

---

lib/Paws/Net/S3Signature.pm

I was getting my requests denied when trying to use Paws::S3 with temporary credential I received from assuming a role.  This fixes it.

add support for making S3 calls using temporary credentials

---

t/lib/TestResponseRecorder.pm

Given the serious bugs raised in the Hash::MD5 queue, this module is not ready for prime time yet -- take a more conservative approach that is known to work when calculating the checksum.
https://rt.cpan.org/Ticket/Display.html?id=107028
https://rt.cpan.org/Ticket/Display.html?id=107027

calculate checksum of hash using JSON serialization, rather than Hash::MD5

---

cpanfile
t/04_credentials.t

- Hash::MD5 is no longer used, so I removed it from test prereqs.
- I couldn't see where Data::Printer was being used in tests, so I removed that too.
Also, I wonder what the problem was with `[Test::Compile]`? Is there something I can fix?  If the compile test was generated as a normal test (not using install mode), then t/01-load.t could be deleted and allow for the removal of Test::Class::Moose as a prerequisite -- this is a rather large distribution with other dependencies and is only being used to load all the classes in the distribution.

Remove some unneeded test prereqs

---

t/lib/FileCaller.pm

The FileCaller class can be used for testing using sample API responses.
It gets the information from a static YAML file with the basic fields
needed to fake a real API response.
You can use any of the TestMakerCaller classes to obtain a sample of the
result XML or JSON from an API call and feed it to the 'content' field
of the test YAML file.

Add FileCaller for testing purposes

---

examples/sts-saml.pl
lib/Paws/Credential/AssumeRoleWithSAML.pm
lib/Paws/Credential/None.pm

Hi,
I've been trying to STS federated login to work, as in http://blogs.aws.amazon.com/security/post/Tx1LDN0UBGJJ26Q/How-to-Implement-Federated-API-and-CLI-Access-Using-SAML-2-0-and-AD-FS
I saw that Boto handled this by adding `NO_CREDENTIALS_PROVIDED = object()` to boto/provider.py and used that for the creds in `sts/connection.py`, so I've taken a similar approach. I added a stub `Paws::Credential::None` and it is automatically used when calling `Paws->creds_service` rather than `service`. 
I put that straight in auto-lib/Paws instead of the template because I'm still playing around, and I'm not sure what the best way of handling this is. There's currently a lot of duplication in the `Paws::Credential` space.  Did you have any plans for the STS pieces?
Thanks!

[WIP] STS Federated Login

---

t/04_credentials.t

Also add AWS_DEFAULT_PROFILE to the list of cleared environment
variables.  This fixes #87.

Localise %ENV entries instead of explicitly resetting

---

lib/Paws/Credential/AssumeRoleWithSAML.pm
lib/Paws/Credential/None.pm
t/10_generate_test_cases.pl

Removing a couple of package BLOCK and one keys REF makes the tests pass
on Perl 5.10.

Make compatible with Perl 5.10

---

lib/Paws/API/Retry.pm

This patch adds the ```__default__``` retry section of ```botocore/botocore/data/_retry.json``` to ```Retry.pm```.
I have reproduced the structures used on the "rules" for homogeneity. I don't know if it is the best option.
I also have a doubt about the best place for the ```default_rules```. Perhaps it should go to the Class/Module level, but my perl knowledge is still limited and am not sure on what is the best way to proceed.
I have tried this patch on a program that was giving me ```Rate Exceeded``` exceptions from time to time with only one attempt to do the call. Now it does the retries and I am not seeing the exception again :)
Hope this helps!

Add rules for default retries

---

lib/Paws/API/Caller.pm

Bug fix, where GetObjectOutput was not setting response headers attributes.

Set response headers

---

lib/Paws/Net/XMLResponse.pm
t/10_responses/sqs-service-unavailable.response
t/10_responses/sqs-service-unavailable.response.test.yml

I've seen scenarios where AWS (specifically SQS) will return the following response:
```
HTTP/1.1 503 Service Unavailable
Server: Server
Connection: close
Content-Length 30
Content-Type: text/xml
ETag: "56c51349-1e"
Date: Fri, 19 Aug 2016 16:39:56 GMT
<ServiceUnavailableException/>
```
This causes an unhanded exception in XMLResponse which doesn't make sense to me. There are other places in Paws where an empty request ID is passed to the exception object so I thought we could reuse it.
This will allow retry roles to pick up on the error and retry vs Paws users having to implement their own retry.

Set request ID to empty string when it doesn't exist on response

---

cpanfile
lib/Paws/Net/S3Signature.pm

Digest::SHA is core and supports SHA-256, this removes the dependency on CryptX.

Use Digest::SHA instead of Crypt::Digest::SHA256

---

lib/Paws/Net/RestXmlCaller.pm

Set the correct XML element names where indicated by the schema. (See 'Events'=>'Event' and 'LambdaFunctionArn'=>'CloudFunction' of Paws::S3::LambdaFunctionConfiguration)

Update RestXmlCaller.pm to fix malformed xml schema issues for Paws::S3::PutBucketNotificationConfiguration

---

lib/Paws/Net/RestXmlCaller.pm

`RestXmlCaller->_call_uri` may return a URI with a query
component. `URI->query_form` will replace an existing query with
whatever you pass to it.
The combination of these two facts means that the URI for
ListObjectsV2 lost its `?list-type=2`, and the response was in the
older v1 format, making pagination impossible.
There are 70 request types that have query components in their
`_api_uri`, they should all work better now.

Fix Issue #105 keep params from URI template

---

builder-lib/Paws/API/Builder/restxml.pm
lib/Paws/API.pm
lib/Paws/API/Caller.pm
lib/Paws/Net/RestXmlCaller.pm

This addresses [issue 131](https://github.com/pplu/aws-sdk-perl/issues/131) by adding a Trait, "ParamsInHeader" for free-form AWS parameters that are passed in the request header (e.g. S3 Metadata). The REST XML request builder is updated to look for that trait and act accordingly. 
Testing done: I created a sketch with my company's AWS credentials and was able to put an object with S3 metadata specified, like so:
```
use 5.016;
use FindBin qw($Bin);
use lib qq($Bin/../auto-lib);
use lib qq{$Bin/../lib};
use Paws;
my $s3 = Paws->service('S3', region => 'us-east-1');
my $bucket = 'mah-bukkit';
my $key = 'Paws-test-foobar';
my $data = 'my data';
$s3->PutObject( Bucket => $bucket, Key => $key, Body => $data, Metadata => { filename => 'foobar.doc' } );
my $object = $s3->GetObject( Bucket => …
```

Fix Issue #131: S3 Metadata

---

Changes
lib/Paws/Credential/AssumeRole.pm
lib/Paws/Credential/AssumeRoleWithSAML.pm
lib/Paws/Credential/InstanceProfile.pm
lib/Paws/Credential/STS.pm

In my tests this improved speed on each api call by a little under a millisecond.
Would close #158

Speed up Credential Refreshing

---

lib/Paws/Credential/Explicit.pm
t/04_credentials.t

It's not a recommended practice, but somethimes you need to create
credentials and get the access key and the secret key from parameters.
Until now, we were (ab)using Paws::Credential::Environment as a
workaround, but this new class should solve the issue in a more elegant
way.

Add Explicit Credentials class

---

lib/Paws/Net/JsonResponse.pm
lib/Paws/Net/RestJsonResponse.pm
lib/Paws/Net/RestXMLResponse.pm

This fixes retries on 503 errors that don't have an `x-amzn-requestid` header or a `__type` attribute.

Handle missing code and response ID in errors

---

lib/Paws/Net/RestJsonResponse.pm

e.g. EFS DeleteFileSystem errors have no message

prevent empty messages as type is defined as string

---

examples/support.pl

Add a comment to clarift that support always uses the same region as
stated in the docs

Add a comment clarify region

---

lib/Paws/Net/RestXmlCaller.pm

In the context of calling PutObject:
In lib/Paws/Net/RestXmlCaller.pm
```perl
if (my $xml_body = $self->_to_xml_body($call)){
$request->content($xml_body);
}
```
sets the body to undef and then the next call `$self->_to_header_params($request, $call);` which calculates the MD5 checksum always calculates a checksum of the empty string.
This is because PutObject 
```perl
class_has _stream_param => (is => 'ro', default => 'Body');
```
and so the content is only set in the code after `_to_header_params` is called
By moving the `_to_header_params` call to JUST BEFORE the `sign` call we can ensure that if there is content to digest it will have been set
PutObject is a *bread and butter* call. **PLEASE** consider pushing this out as a patched release with urgency

Only set ContentMD5 header when content has been set

---

builder-lib/Paws/API/Builder.pm

Prevent service calls docs to show as code blocks.

Prevent service calls docs to show as code blocks

---

builder-lib/Paws/API/Builder.pm

For convenience, provide a link to ease going back to the service page when checking a given call documentation.

Add convenience links to service on call docs

---

cpanfile

Test t/25_error_on_malformed_response.t failing due to XML::Simple 2.20.
Updating to 2.21 allows it to pass.

add XML::Simple version dep

---

lib/Paws/Credential/Environment.pm

POD documentation for Paws::Credential::Environment has typo, this changes it to actually match with the name of the package.

Fix typo on Pod documentation

---

lib/Paws/Net/S3Signature.pm

When trying to use Paws::S3 with an S3 compatible server (minio in this case)
which listens on a non-default http(s) port, invalid signatures are generated
because only the `host` part of the endpoint URI is used.
AWS and minio server side use `host:port` when the port isn't the
default port (443).
Confirmed behaviour with aws cli/boto and minio's python client.

Make valid signatures for S3-alike services on non-default ports

---

Changes
t/04_credentials/test_cred_process
t/04_credentials/test_cred_process.expiry
t/04_credentials/test_cred_process.fail
t/04_credentials/test_cred_process.noversion

Paws 0.37 is failing lots of CPAN Testers: http://matrix.cpantesters.org/?dist=Paws+0.37
Fix test suite so that credentials_process tests don't need extra modules (sometimes the
perl being tested is not the same perl that #!/usr/bin/env perl returns, so it may not
have JSON::MaybeXS installed
Should solve #248 and #251

Implement the output of the credentials process scripts in pure Perl

---

README.md
cpanfile

This is just a suggestion. Dist::Zilla deps even in the develop phase tend to clutter up dependency management and analysis, and are unnecessary for most contributors. Thus it's usually best to just document how to use dzil to install the needed deps for its workflow, as dzil can manage this itself based on the dist.ini. I believe you are only using dzil for packaging, not running tests or anything, so it should not affect any of the rest of the development setup (and should significantly lessen the amount of time to install development deps for those who don't need it).

remove dzil deps from cpanfile and provide instructions for dzil installation

---

lib/Paws/Net/MojoAsyncCaller.pm

FIxes error when use MojoAsyncCaller:
```
Mojo::Reactor::Poll: I/O watcher failed: Can't locate object method "new" via package "Paws::Net::APIResponse" (perhaps you forgot to load "Paws::Net::APIResponse"?) at /usr/lib/perl5/Paws/Net/MojoAsyncCaller.pm line 63.
```

Added missed use of Paws::Net::APIResponse to MojoAsyncCaller

---

lib/Paws/API/Caller.pm

This class uses Paws->load_class internally but does not declare it with
a 'use'. Most of the time it's ok because you already have Paws loaded,
but if you try to load Paws::API::Caller alone and call one of it's
methods, it will fail.
Adding this 'use Paws' prevents this eventual problem, and also makes a
bit clearer what depends on what on the Paws ecosystem.

Make 'Paws' dependency explicit on Paws::API::Caller

---

lib/Paws/API/Caller.pm

Revert "Make 'Paws' dependency explicit on Paws::API::Caller"

---

.proverc
Makefile

This makes it easier to run only selected tests by
$ carton exec -- prove t/foo.t

Move `prove` arguments to .proverc

---

lib/Paws/Credential/InstanceProfile.pm

The IAM role documentation says that new credentials will be made available at least five minutes before the current ones expire (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials).  I think it would be beneficial to take advantage of this grace period.
My own use case is that because `Paws::S3` is not quite production ready, I have been using `Paws::Credential::ProviderChain` _a la carte_ to get AWS keys for S3 requests.  But I'm having a problem that due to the code logic, which includes multiple requests and can last a few seconds, there is sometimes enough of a delay that if it's close to the expiration time they will start failing.
This could be worked around, but there are other cases where using the grace period …

Use grace period for renewing IAM role credentials.

---

bin/open_aws_console
bin/paws
bin/paws_make_testcase

setting it to /usr/bin/perl makes EUMM update the #! during install

Patch bin scripts to support the #! Makefile.PL was invoked with

---

bin/paws
bin/paws_make_testcase

bin/paws binary seem to be designed for end
users and should not add an unsafe directory
to @INC. As we cannot predict where will be
the 'auto-lib' and 'lib' directories.
bin/paws_make_testcase is a tool for the distribution
and should not be shipped (view #309), we can add lib
to it to preserve its current behavior.

bin/paws should not add lib to @INC

---

lib/Paws/Net/RestXmlCaller.pm

Encountered warnings during 
```
$s3->PutObjectACL( 
Bucket =>, 
Key =>, 
ACL => 'bucket-owner-full-control');
```
This gets rid of the warnings and `PutObjectACL` still works

Fix Uninitialized Value warnings

---

auto-lib/Paws.pm
lib/Paws/API/Caller.pm
lib/Paws/Net/EC2Caller.pm
lib/Paws/Net/JsonCaller.pm
lib/Paws/Net/QueryCaller.pm
lib/Paws/Net/RestJsonCaller.pm
lib/Paws/Net/RestXmlCaller.pm
t/lib/TestMakerCaller.pm
templates/paws.tt

All three `new_with_coercions` and `to_hash` and `is_internal_type` are called in multiple places both in Paws code and for clients using Paws.         
Having them in Paws::API::Caller it's a bit awkward for me, because I don't associate these utilities to the caller (which, as far as I understand, is designed to allow caller pluggability).                          
I've considered creating a Paws::Util or something like that, but it looked to me that `load_class`, that was already under Paws.pm, was the same kind of utility, and therefore I've put the three of them together.

Add common utils to paws

---

Changes
lib/Paws/Net/APIRequest.pm
t/05_service_calls.t

Fix to solve issue appeared after 0.40 (documented in #325).

Make HTTP content an empty string by default

---

.travis.yml

As explained in issue #362 Travis build is broken due a long log output. This is caused by an `auto` mode of  [travis-helpers](https://github.com/travis-perl/helpers). Passing to manual mode as the documentation suggest, makes the build work another time.
More information in the issue mentioned above.

Fix travis build pipeline

---

lib/Paws/Net/QueryCaller.pm
t/05_service_calls.t

This contribution allows passing empty Arrays to calls to AWS services that are using `Paws::Net::QueryCaller` class
This changes should fix issue #376 allowing Paws to clear CloudFormation Stack Tags

Handle empty arrays in Paws::Net::QueryCaller parameters

---

.github/workflows/test.yml
t/13_client_connect_errors.t
t/14_dns_client_errors.t
t/15_timeouts.t
t/28_retries_mojoasynccaller.t

Currently, CI of aws-sdk-perl is running on travis-ci.org https://travis-ci.org/github/pplu/aws-sdk-perl
But Travis-ci.org shut down will occur on May 31, 2021. (ref. https://blog.travis-ci.com/2021-05-07-orgshutdown)
So we should migrate to travis-ci.com or another CI service.
I propose GitHub Actions because it looks that the new plan of travis-ci.com is not OSS friendly.
(ref. https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)
The new plan provides OSS credits, however we need to contact to travis support team.
And contributors can't use OSS credits on their forked repositories.
On the other hand, all GitHub Users can use GitHub Actions for free on their public repositories.
It makes contributing easier.

introduce GitHub Actions

---

dist.ini

When a distribution is uploaded to the PAUSE system, it parses every .pm file
for a $VERSION declaration in order to determine the version number to be used 
in the cpan index next to that package name. However, this parsing can be
skipped entirely if data is provided in META.* indicating how to perform the
indexing (as documented at
https://metacpan.org/pod/CPAN::Meta::Spec#provides). A dzil plugin can be used
to insert this metadata using the distribution version.

Allow PAUSE to index this distribution much faster

---

builder-lib/Paws/API/Builder.pm

I'm sure others have noticed that there is a mess of diffs every single time you regenerate the auto-lib directory.  This fixes that inconsistency so the diff of auto-lib actually represents real changes to the generated source and not just a million lines of noisy spacing differences.

Fix inconsistent class generation

---

builder-bin/gen_classes.pl
cpanfile

On my personal system, this cuts `make gen-classes` down from 25 minutes to 7.
There's a lot of options for doing this, my first run just used some arguments to xargs so if you'd prefer something besides Parallel::ForkManager happy to rework it.

gen-classes: introduce Parallel::ForkManager for faster gen

---

cpanfile
lib/Paws/Credential/File.pm

Config::INI and specifically its requirement on Mixin::Linewise
require perl v5.12 so let's use Config::AWS instead.  There's actually
some lesser used syntax that Config::INI didn't support anyways:
Given a file like this:
[profile testing]
aws_access_key_id = foo
aws_secret_access_key = bar
region = us-west-2
s3 =
max_concurrent_requests=10
max_queue_size=1000
Config::AWS (properly) decodes to:
'testing' => {
'aws_access_key_id' => 'foo',
'region' => 'us-west-2',
's3' => {
'max_queue_size' => '1000',
'max_concurrent_requests' => '10'
},
'aws_secret_access_key' => 'bar'
}
whereas Config::INI decodes to:
'profile testing' => {
'aws_access_key_id' => 'foo',
'aws_secret_access_key' => 'bar',
's3' => '',
'max_concurrent_requests' => '10',
'region' => 'us-west-2',
'max_queue_size' => '1000'
} …

Move to Config::AWS to support perl v5.10

---

auto-lib/Paws.pm
lib/Paws/Credential/InstanceProfile.pm
lib/Paws/Credential/InstanceProfileV2.pm
lib/Paws/Credential/ProviderChain.pm
t/04_credentials.t
t/lib/Test04/StubUAForMetadata.pm
t/lib/Test04/StubUANoMetadata.pm
templates/default/paws_pm.tt

Implement support of new version of AWS Instance Metadata Service.
Update calls to be the same as described at the following document:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-v2-how-it-works

Support AWS Instance Metadata Service V2 (IMDSv2)
